// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9X0ekaXM2FfAivqvipYiBJMBYrVF8po',
    appId: '1:1049420541160:web:0a08f2a5dd44c37ef2ed5d',
    messagingSenderId: '1049420541160',
    projectId: 'flutterphone-706d3',
    authDomain: 'flutterphone-706d3.firebaseapp.com',
    storageBucket: 'flutterphone-706d3.firebasestorage.app',
    measurementId: 'G-BPHKZ9SBHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtm6P9-VxbCRmf9L6_kf192M-_veH9Ck',
    appId: '1:1049420541160:android:ad66236d330180a1f2ed5d',
    messagingSenderId: '1049420541160',
    projectId: 'flutterphone-706d3',
    storageBucket: 'flutterphone-706d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyx9Fit__-GONXvKXRAcnxbiWigntnVl0',
    appId: '1:1049420541160:ios:cdf0ad03aeb433d9f2ed5d',
    messagingSenderId: '1049420541160',
    projectId: 'flutterphone-706d3',
    storageBucket: 'flutterphone-706d3.firebasestorage.app',
    iosBundleId: 'com.example.firbaseFile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyx9Fit__-GONXvKXRAcnxbiWigntnVl0',
    appId: '1:1049420541160:ios:cdf0ad03aeb433d9f2ed5d',
    messagingSenderId: '1049420541160',
    projectId: 'flutterphone-706d3',
    storageBucket: 'flutterphone-706d3.firebasestorage.app',
    iosBundleId: 'com.example.firbaseFile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx9X0ekaXM2FfAivqvipYiBJMBYrVF8po',
    appId: '1:1049420541160:web:edcc9f7b55398765f2ed5d',
    messagingSenderId: '1049420541160',
    projectId: 'flutterphone-706d3',
    authDomain: 'flutterphone-706d3.firebaseapp.com',
    storageBucket: 'flutterphone-706d3.firebasestorage.app',
    measurementId: 'G-NCQJ5HZ0HW',
  );

}